FROM ghcr.io/dockhippie/minecraft-vanilla:1.20.6-amd64@sha256:e8145b78ba1c51b71cb83903d8b65f7a1df83ae9d3d4625319551a6279a1a52a AS build

EXPOSE 25565 25575

ENV NEOFORGE_VERSION 20.6.139
ENV NEOFORGE_URL https://maven.neoforged.net/releases/net/neoforged/neoforge/${NEOFORGE_VERSION}/neoforge-${NEOFORGE_VERSION}-installer.jar

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y libatomic1 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  curl --create-dirs -sLo /usr/share/minecraft/neoforge-${NEOFORGE_VERSION}-installer.jar ${NEOFORGE_URL} && \
  cd /usr/share/minecraft && \
  mkdir mods && \
  java -jar neoforge-${NEOFORGE_VERSION}-installer.jar --installServer && \
  rm -f neoforge-${NEOFORGE_VERSION}-installer.jar neoforge-${NEOFORGE_VERSION}-installer.jar.log run.bat run.sh

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container && \
  chmod +x /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
