FROM ghcr.io/dockhippie/minecraft-vanilla:1.20.2-arm64@sha256:1bef1f2cb32e3c04a98b29696ba2a7ae3a9309d23e4d725d67bbf73d13712fb7 AS build

EXPOSE 25565 25575

ENV NEOFORGE_VERSION 20.2.86
ENV NEOFORGE_URL https://maven.neoforged.net/releases/net/neoforged/neoforge/${NEOFORGE_VERSION}/neoforge-${NEOFORGE_VERSION}-installer.jar

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y libatomic1 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  curl --create-dirs -sLo /usr/share/minecraft/neoforge-${NEOFORGE_VERSION}-installer.jar ${NEOFORGE_URL} && \
  cd /usr/share/minecraft && \
  mkdir mods && \
  java -jar neoforge-${NEOFORGE_VERSION}-installer.jar --installServer && \
  rm -f neoforge-${NEOFORGE_VERSION}-installer.jar neoforge-${NEOFORGE_VERSION}-installer.jar.log run.bat run.sh

COPY ./overlay /
