FROM ghcr.io/dockhippie/minecraft-vanilla:1.20.5-amd64@sha256:abdba36253ffa5174e2248a9dc26d8e3981f5955c4e1b4031608ea493845beb6 AS build

EXPOSE 25565 25575

ENV NEOFORGE_VERSION 20.5.21-beta
ENV NEOFORGE_URL https://maven.neoforged.net/releases/net/neoforged/neoforge/${NEOFORGE_VERSION}/neoforge-${NEOFORGE_VERSION}-installer.jar

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y libatomic1 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  curl --create-dirs -sLo /usr/share/minecraft/neoforge-${NEOFORGE_VERSION}-installer.jar ${NEOFORGE_URL} && \
  cd /usr/share/minecraft && \
  mkdir mods && \
  java -jar neoforge-${NEOFORGE_VERSION}-installer.jar --installServer && \
  rm -f neoforge-${NEOFORGE_VERSION}-installer.jar neoforge-${NEOFORGE_VERSION}-installer.jar.log run.bat run.sh

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container && \
  chmod +x /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
